name: Sincronizar Catálogo (Diario Madrugada)

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar API Catalogo Vercel
        env:
          MY_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
        run: |
          curl -X GET "https://xml-json-feed-magento-7ajapw2fx.vercel.app/api/feed?mode=catalog" \
          -H "Authorization: Bearer $MY_SECRET_TOKEN"